name: Integration Tests

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  call-workflow:
    uses: ./.github/workflows/test-plugin.yml
    with:
        triton-shared-ref: ${{ github.ref }}
